title: "Weitao Jiang's Website"
description: "PhD Student at SUSTech"
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://weitaojiang.github.io/webpage/" # Your website URL

# Personal Info
author: 
  name: "Weitao Jiang"
  pronouns: "He/His"
  position: "PhD Student in Intelligent Manufacturing and Robotics"
  university: "Southern University of Science and Technology, Shenzhen, China"
  advisor: "Prof. Seungwoo Je"
  profile_image: "/assets/images/image.png"
  
# Social Links
social_links:
  google_scholar: "https://scholar.google.com/citations?user=MIUckX0AAAAJ&hl=zh-CN"
  orcid: "https://orcid.org/my-orcid?orcid=0000-0002-3770-9027"
  email: "mailto:Weitaojiangdesign@gmail.com"
  cv: "https://drive.google.com/file/d/14Vqc5PdRsVkfaDHlzZtZAIDmSxzNmX5p/view?usp=share_link"

# Build settings
theme: minima
